# Generated by Django 6.0 on 2025-12-07 05:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='채팅 세션 ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='사용자 ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
                ('role', models.CharField(max_length=10, verbose_name='역할')),
                ('content', models.TextField(verbose_name='메시지 내용')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지 목록',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChbNotice',
            fields=[
                ('notice_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='공지사항 고유 ID')),
                ('board_type', models.CharField(db_index=True, max_length=100, verbose_name='게시판 종류')),
                ('title', models.CharField(max_length=512, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('source_url', models.URLField(max_length=512, verbose_name='원본 URL')),
                ('post_date', models.DateField(verbose_name='게시일')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='DB 추가일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '충북대 공지사항',
                'verbose_name_plural': '충북대 공지사항 목록',
                'db_table': 'chat_chbnotice',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='사용자 ID')),
                ('token_data', models.TextField(verbose_name='토큰 데이터 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '구글 캘린더 토큰',
                'verbose_name_plural': '구글 캘린더 토큰 목록',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='사용자 ID')),
                ('title', models.CharField(max_length=255, verbose_name='일정 제목')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='구글 캘린더 이벤트 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '사용자 일정',
                'verbose_name_plural': '사용자 일정 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='NoticeRagIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(verbose_name='청크 인덱스')),
                ('text', models.TextField(verbose_name='청크 텍스트')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='벡터 임베딩')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='chat.chbnotice', verbose_name='공지사항')),
            ],
            options={
                'verbose_name': '공지사항 RAG 인덱스',
                'verbose_name_plural': '공지사항 RAG 인덱스 목록',
                'db_table': 'notice_rag_index_table',
                'unique_together': {('notice', 'chunk_index')},
            },
        ),
    ]
