# Generated by Django 5.0.6 on 2025-11-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawDocument',
            fields=[
                ('doc_type', models.CharField(db_index=True, max_length=20, verbose_name='문서 유형')),
                ('document_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='문서 고유 ID')),
                ('title', models.CharField(max_length=512, verbose_name='문서 제목')),
                ('content', models.TextField(verbose_name='문서 본문 (청킹 및 임베딩 대상)')),
                ('source_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='출처 URL')),
                ('enforcement_date', models.CharField(max_length=8, verbose_name='시행/선고일자 (YYYYMMDD)')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='추가일')),
                ('case_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='사건번호')),
                ('court_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='법원명')),
                ('law_article_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='조항 번호')),
            ],
            options={
                'verbose_name': '통합 법률 문서',
                'verbose_name_plural': '통합 법률 문서 목록',
            },
        ),
    ]
