# Generated by Django 5.2.8 on 2025-11-09 12:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_lawdocument_case_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawdocument',
            name='vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='문서 벡터 임베딩'),
        ),
    ]
