# Generated by Django 5.2.8 on 2025-11-27 06:13

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_lawdocument_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_chunk', models.TextField(verbose_name='텍스트 청크')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='청크 메타데이터')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768, verbose_name='청크 벡터 임베딩')),
            ],
            options={
                'verbose_name': 'RAG 검색 인덱스',
                'verbose_name_plural': 'RAG 검색 인덱스 목록',
                'db_table': 'rag_index_table',
            },
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='vector',
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='content',
            field=models.TextField(verbose_name='문서 본문 (원본 텍스트)'),
        ),
    ]
