# Generated by Django 5.2.8 on 2025-11-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_chbnotice_rename_ragindex_noticeragindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chbnotice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='현재 활성 상태'),
        ),
    ]
