# Generated by Django 6.0 on 2025-12-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chbnotice_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='사용자 ID')),
                ('title', models.CharField(max_length=512, verbose_name='일정 제목')),
                ('start_date', models.DateField(verbose_name='시작 날짜')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료 날짜')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '개인 일정',
                'verbose_name_plural': '개인 일정 목록',
                'ordering': ['start_date'],
            },
        ),
    ]
