# Generated by Django 6.0 on 2025-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='사용자 ID')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(verbose_name='리프레시 토큰')),
                ('token_expiry', models.DateTimeField(verbose_name='토큰 만료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '구글 캘린더 토큰',
                'verbose_name_plural': '구글 캘린더 토큰 목록',
            },
        ),
        migrations.AddField(
            model_name='userevent',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='구글 캘린더 이벤트 ID'),
        ),
    ]
