# Generated by Django 5.2.7 on 2025-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=300)),
                ('court_name', models.CharField(max_length=100)),
                ('judgment_date', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=100)),
                ('content_summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(max_length=200)),
                ('article_num', models.CharField(max_length=50)),
                ('article_title', models.CharField(blank=True, max_length=200)),
                ('article_content', models.TextField()),
                ('hseq', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
