# Generated by Django 5.0.7 on 2025-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("law_name", models.CharField(max_length=200)),
                ("article_num", models.CharField(max_length=50)),
                ("article_title", models.CharField(max_length=200)),
                ("article_content", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="CaseLaw",
        ),
    ]
