# Generated by Django 5.0.7 on 2025-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_lawarticle_delete_caselaw"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_title", models.CharField(max_length=300)),
                ("court_name", models.CharField(max_length=100)),
                ("judgment_date", models.CharField(max_length=50)),
                ("case_number", models.CharField(max_length=100)),
                ("content_summary", models.TextField(blank=True)),
                ("full_text", models.TextField(blank=True)),
                ("references", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="lawarticle",
            name="article_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
