# Generated by Django 5.2.6 on 2025-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caselaw_alter_lawarticle_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawarticle',
            name='hseq',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
