# Generated by Django 5.0.6 on 2025-11-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=255, verbose_name='사용자 세션 ID')),
                ('question', models.TextField(verbose_name='사용자 질문')),
                ('answer', models.TextField(verbose_name='챗봇 답변')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='문서 제목')),
                ('content', models.TextField(verbose_name='문서 본문')),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='출처 URL')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='추가일')),
            ],
        ),
    ]
