# Generated by Django 5.0.6 on 2025-11-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_lawdocument_delete_sourcedocument_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
