# Generated by Django 5.2.8 on 2025-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawdocument',
            name='case_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='사건번호'),
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='법원명'),
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='doc_type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='문서 유형'),
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='document_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='문서 고유 ID'),
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='enforcement_date',
            field=models.CharField(max_length=255, verbose_name='시행/선고일자 (YYYYMMDD)'),
        ),
        migrations.AlterField(
            model_name='lawdocument',
            name='law_article_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='조항 번호'),
        ),
    ]
