# Generated by Django 5.2.8 on 2025-11-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_ragindex_remove_lawdocument_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='채팅 세션 ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='사용자 ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
                ('role', models.CharField(max_length=10, verbose_name='역할')),
                ('content', models.TextField(verbose_name='메시지 내용')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지 목록',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChbNotice',
            fields=[
                ('notice_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='공지사항 고유 ID')),
                ('board_type', models.CharField(db_index=True, max_length=100, verbose_name='게시판 종류')),
                ('title', models.CharField(max_length=512, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문 내용 (청크 분할 대상)')),
                ('source_url', models.URLField(max_length=512, verbose_name='원본 URL')),
                ('post_date', models.DateField(verbose_name='게시일')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='DB 추가일')),
            ],
            options={
                'verbose_name': '충북대 공지사항',
                'verbose_name_plural': '충북대 공지사항 목록',
                'ordering': ['-post_date'],
            },
        ),
        migrations.RenameModel(
            old_name='RagIndex',
            new_name='NoticeRagIndex',
        ),
        migrations.DeleteModel(
            name='LawDocument',
        ),
        migrations.AlterModelOptions(
            name='noticeragindex',
            options={'verbose_name': '공지사항 RAG 인덱스', 'verbose_name_plural': '공지사항 RAG 인덱스 목록'},
        ),
        migrations.AlterModelTable(
            name='noticeragindex',
            table='notice_rag_index_table',
        ),
    ]
