# Generated by Django 5.0.6 on 2025-11-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=255, verbose_name='사용자 세션 ID')),
                ('question', models.TextField(verbose_name='사용자 질문')),
                ('answer', models.TextField(verbose_name='챗봇 답변')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
            ],
            options={
                'verbose_name': '대화 기록',
                'verbose_name_plural': '대화 기록 목록',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=255, verbose_name='사용자 세션 ID')),
                ('file', models.FileField(upload_to='user_uploads/', verbose_name='업로드 파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='추출된 텍스트')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시각')),
                ('is_rag_ready', models.BooleanField(default=False, verbose_name='RAG 처리 완료 여부')),
            ],
            options={
                'verbose_name': '사용자 업로드 문서',
                'verbose_name_plural': '사용자 업로드 문서 목록',
            },
        ),
    ]
